### ISSUE TITLE
allocate_udp_test failing

### ISSUE THREAD

**Issue by debalance** [processone/stun#10]
Hi,
until recently, allocate_udp_test only failed on hurd-i386 (which I didn't much care about, see https://bugs.debian.org/820393), but now it is also happening on amd64, which is rather important.
It might be because Debian Sid has Erlang 20 now.

Full build log attached.

[erlang-p1-stun_1.0.12-1_amd64.build.txt](https://github.com/processone/stun/files/1139845/erlang-p1-stun_1.0.12-1_amd64.build.txt)

**Comment by prefiks** [comment]
I think commit 4b28e996bb8e82164e633c25fe77de36ddc3638c should fix this.

**Comment by debalance** [comment]
It does, thank you!
