### ISSUE TITLE
lots of error_logger:info_msg logs

### ISSUE THREAD

**Issue by facundoolano** [processone/stun#15]
Hi, I'm using this app to provide a STUN/TURN server for a WebRTC client. When a client connects I get a lot of logs like:

```
accepted long-term STUN authentication for user
created TURN allocation for user
deleting TURN allocation for  user
created/updated TURN permission for user 
``` 

Those look as debug logs to me, is there a special reason for them to use `error_logger:info_msg` directly instead of `?dbg()`?

I can send a PR turning them to `?dbg` if you are OK with it.

**Comment by zinid** [comment]
The problem with `?dbg` is that you cannot enable debug in runtime, you need to recompile the package completely. Very inconvenient.

**Comment by zinid** [comment]
OK, I changed my mind, feel free to create a PR.
