### ISSUE TITLE
IPv6 for ICE

### ISSUE THREAD

**Issue by Neustradamus** [processone/stun#26]
Can you add IPv6 support in more IPv4?

There are for ICE:
- RFC 5245 - ICE: https://tools.ietf.org/html/rfc5245
- RFC 5768 – ICE–SIP: https://tools.ietf.org/html/rfc5768
- RFC 6336 – ICE–IANA Registry: https://tools.ietf.org/html/rfc6336
- RFC 6544 – ICE–TCP: https://tools.ietf.org/html/rfc6544
- RFC 8445 - ICE-NAT: https://tools.ietf.org/html/rfc8445

**Comment by Neustradamus** [comment]
@weiss: Why have you closed the ticket?

**Comment by weiss** [comment]
ICE is a set of client-side specs.

**Comment by Neustradamus** [comment]
@weiss: Yes, it will be nice to update with all supported RFCs and specify all ICE which work in link with STUN/TURN;
- https://www.process-one.net/en/ejabberd/protocols/
