### ISSUE TITLE
hex.pm documentation page for stun shows error message

### ISSUE THREAD

**Issue by aquap** [processone/stun#29]
The hex.pm page for stun points at https://hexdocs.pm/stun/ and is returning errors with the text
```
  PAGE NOT FOUND
  Is something wrong with the package documentation? Open an issue on the project 
  the documentation belongs to. Most packages link to their repository from their 
  hex.pm page.
```
This impacts all releases of the stun documentation there from verson 1.0.31 as far as I can tell.

**Comment by badlop** [comment]
The same happens with all the other erlang libraries from http://processone.github.io/

**Comment by badlop** [comment]
Usually documentation for Erlang programs is generated using EDoc. However, stun and the other libraries have few information in edoc format.

Maybe it's preferable to convert README.md to html and publish that in the hexdocs page...

**Comment by badlop** [comment]
This is fixed in this library with https://github.com/processone/stun/commit/6971ed5913972a1487622ebe04a410bd753ffd9d and in other libraries with equivalent commits (they are being updated when other more important changes are being committed).
