### ISSUE TITLE
no longer compiles with elixir 1.0.5

### ISSUE THREAD

**Issue by knewter** [processone/stun#5]
I haven't recompiled ejabberd with elixir in a couple of weeks.  Now, when I try to compile it, I get the following error:

```
==> p1_stun (compile)
src/stun_listener.erl:39: type dict() undefined
ERROR: compile failed while processing /home/jadams/projects/concur.io/concurio_jabber/deps/p1_stun: rebar_abort
** (Mix) Could not compile dependency p1_stun, /home/jadams/bin/rebar command failed. If you want to recompile this dependency, please run: mix deps.compile p1_stun
```

**Comment by knewter** [comment]
I'm sorry, it looks like this error was already corrected 18 days ago and I had a bad version specified in my mix.lock.  Sorry for the noise :(

**Comment by mremond** [comment]
No problem, thanks for the update :)
